### ISSUE TITLE
Handle the tailrecursion in the game engine

### ISSUE THREAD

**Issue by mosser** [ace-design/island#54]

**Comment by mosser** [comment]
The Engine.play method is not tail recursive du to a try/catch preventing tailrec optimization. It results in an StackOverflow exception when a player uses a lot of different actions. 

Here is a prototypical example that reproduce the issue:
object TailRecursion extends App {
  def recursion(x: Int): Int = recursion(x+1)
  //recursion(0) // tail recursive => OK ("infinite" execution)

  def catchRec(x: Int): Int = try { catchRec(x+1) } catch { case e: Exception => -1 }
  catchRec(0)    // !tail recursive => immediate StackOverflowError
}

**Comment by fabienfoerster** [comment]
object TailRecursion extends App {
  def recursion(x: Int): Int = recursion(x+1)
  //recursion(0) // tail recursive => OK ("infinite" execution)

  def catchRec(x: Int): Int = try { recursion(x) } catch { case e: Exception => -1 }
  catchRec(0) // tail recursive => OK("infinite" execution)
}

This should do the trick, no ?
