### ISSUE TITLE
Javascript visualization

### ISSUE THREAD

**Issue by mosser** [ace-design/island#56]
Improve Pascal's tung visualization algorithm to support the new actions for 2015-2016

**Comment by ktung** [comment]
Il ne fonctionne plus ?

**Comment by mosser** [comment]
On a rajouté de nouvelles actions, ils y a une phase aérienne. Un 3A est reparti de ton idée pour proposer quelque chose qui matche avec les nouvelles actions. Je t'ai crédité sur la page du projet pour rappeler qu'a la base c'est grace a toi que ce truc existe :). (http://ace-design.github.io/island/runner/)
